export const movieArray = [
  {
    id: 1,
    title: "Friday the 13th",
    trailer: "cCfO1aB8CIE",
    text: "A group of young adults visit a boarded up campsite named Crystal Lake where they soon encounter the mysterious Jason Voorhees and his deadly intentions.",
    stars: "Jared Padalecki, Amanda Righetti, Derek Mears",
    image: "https://images5.alphacoders.com/442/442591.jpg",
    alt: "a close up of a hockey mask",
    date:  [11,  2,  3,  4,  5,  6,  7,  8,  9,  10],
    time:  ["18:10",  "20:10",  "22:10"],
    param: "Friday-the-13th",
    length: 120,
    release: "13 february 2009",
    releaseDate: {day: 13, month: 2, year: 2009},
    background: "https://wallpapercave.com/wp/wp3940179.jpg",
  },
  {
    id: 2,
    title: "Hellraiser",
    stars: "Stars: Odessa A’zion, Jamie Clayton, Adam Faison",
    release: "28 september 2022",
    releaseDate: {day: 28, month: 9, year: 2022},
    trailer: "oUlgwJNdu2I",
    text: "A take on Clive Barker's 1987 horror classic where a young woman struggling with addiction comes into possession of an ancient puzzle box, unaware that its purpose is to summon the Cenobites.",
    image:
      "https://decider.com/wp-content/uploads/2022/10/HELLRAISER-HULU-REVIEW.jpg?quality=75&strip=all",
    alt: "the face of a woman with symmetrical scars on and spikes protruding from her skin",
    date:  [11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
    time:  ["19:15",  "21:15",  "23:15"],
    length: 122,
    param: "hellraiser",
    background:
      "https://img.hulu.com/user/v3/artwork/eb138082-5c40-4a8f-aa30-3fc66ef615fd?base_image_bucket_name=image_manager&base_image=bb8c33aa-6af6-4303-8cb7-2aa598039a75&size=1600x900&format=jpeg",
  },
  {
    id: 3,
    title: "It",
    stars: "Bill Skarsgård, Jaeden Martell, Finn Wolfhard",
    release: "13 september 2017",
    releaseDate: {day: 13, month: 9, year: 2017},
    trailer: "xKJmEC5ieOk",
    text: "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.",
    image:
      "https://c4.wallpaperflare.com/wallpaper/149/736/981/it-clown-bill-skarsgard-horror-wallpaper-preview.jpg",
    alt: "the face of a grinning clown partially covered by a red balloon",
    date:  [21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
    time:  ["16:20",  "18:20",  "20:20"],
    length: 124,
    param: "jacobs-ladder",
    background: "https://wallpaperaccess.com/full/37961.jpg",
  },
  {
    id: 4,
    title: "Paranormal Activity",
    stars: "Chris J. Murray, Brit Shaw, Ivy George",
    release: "23 oktober 2015",
    releaseDate: {day: 23, month: 10, year: 2015},
    trailer: "zR2cc1BwdmI",
    text: "Using a special camera that can see spirits, a family must protect their daughter from an evil entity with a sinister plan.",
    image:
      "https://images.tbs.com/tbs/$dyna_params/https%3A%2F%2Fi.cdn.tbs.com%2Fassets%2Fimages%2F2019%2F10%2FParanormal-Activity-1920x1080.jpg",
    alt: "a child standing on a bed looking into a large hole in the wall",
    date:  [31,  2,  14,  21,  28],
    time:  ["17:25",  "19:25",  "21:25"],
    length: 126,
    param: "the-shining",
    background:
      "https://images.tbs.com/tbs/$dyna_params/https%3A%2F%2Fi.cdn.tbs.com%2Fassets%2Fimages%2F2019%2F10%2FParanormal-Activity-1920x1080.jpg",
  },
  {
    id: 5,
    title: "The Nun",
    stars: "Demián Bichir, Taissa Farmiga, Jonas Bloquet",
    release: "7 september 2018",
    releaseDate: {day: 7, month: 9, year: 2018},
    trailer: "G7kORFktHnM",
    text: "A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania and confront a malevolent force in the form of a demonic nun.",
    image:
      "https://w0.peakpx.com/wallpaper/307/417/HD-wallpaper-the-nun-movie-the-nun-movies-2018-movies.jpg",
    alt: "the face of an evil looking nun",
    date:  [1,  8,  15,  22,  29],
    time:  ["18:10",  "20:10",  "22:10"],
    length: 128,
    param: "the-mist",
    background: "https://images2.alphacoders.com/936/936582.jpg",
  },
  {
    id: 6,
    title: "The Grudge",
    stars: "Sarah Michelle, GellarJason, BehrClea DuVall",
    release: "14 january 2005",
    releaseDate: {day: 14, month: 1, year: 2005},
    trailer: "O2NKzO-fxwQ",
    text: "An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse, one that locks a person in a powerful rage before claiming their life and spreading to another victim.",
    image:
      "https://c4.wallpaperflare.com/wallpaper/502/400/889/dark-demon-film-grudge-wallpaper-preview.jpg",
    alt: "a dark background showing one staring eye partially covered by hair",
    date:  [3,  10,  17,  24,  31],
    time:  ["16:35",  "18:35",  "20:35"],
    length: 130,
    param: "land-of-the-dead",
    background:
      "https://r4.wallpaperflare.com/wallpaper/445/200/897/bunshinsaba-dark-evil-film-wallpaper-31b293f6a52789800ff3681dfeae5849.jpg",
  },
  {
    id: 7,
    title: "Rings",
    trailer: "uukQ_6szDm8",
    stars: "Matilda Anna, Ingrid LutzAlex, RoeJohnny Galecki",
    release: "1 february 2017",
    releaseDate: {day: 1, month: 2, year: 2017},
    text: "A young woman finds herself on the receiving end of a terrifying curse that threatens to take her life in 7 days.",
    image: "https://wallpapercave.com/wp/wp4357758.jpg",
    alt: "a pale dark haired person stepping out of a tv and reaching out with onehand",
    date:  [4,  11,  18,  25,  1],
    time:  ["14:40",  "18:40",  "22:40"],
    length: 132,
    param: "the-ring",
    background: "https://images2.alphacoders.com/824/824908.jpg",
  },
  {
    id: 8,
    title: "Scream",
    stars: "Neve Campbell,Courteney Cox, David Arquette",
    release: "14 january 2022",
    releaseDate: {day: 14, month: 1, year: 2022},
    trailer: "beToTslH17s ",
    text: "25 years after a streak of brutal murders shocked the quiet town of Woodsboro, Calif., a new killer dons the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town's deadly past.",
    image:
      "https://4kwallpapers.com/images/wallpapers/scream-2022-movies-horror-movies-thriller-black-background-1284x2778-6756.jpg",
    alt: "A ghostly mask with elongated eyes and a drooping mouth",
    date:  [5,  12,  19,  26,  2],
    time:  ["20:45",  "22:45",  "23:45"],
    length: 134,
    param: "scream",
    background: "https://images7.alphacoders.com/122/1226941.jpg",
  },
  {
    id: 9,
    title: "Ouija: Origin of Evil",
    stars: "Elizabeth Reaser, Lulu Wilson, Annalise Basso",
    release: "21 oktober 2016",
    releaseDate: {day: 21, month: 10, year: 2016},
    trailer: "MJIcZGEjjwo",
    text: "Ouija: Origin of Evil is a 2016 American supernatural horror film directed and edited by Mike Flanagan and written by Flanagan and Jeff Howard. The film is a prequel to the 2014 film Ouija and stars Elizabeth Reaser, Annalise Basso, and Henry Thomas.",
    image: "https://images7.alphacoders.com/808/808738.jpg",
    alt: "a child standning in the corner of a room with the floor and walls designed as a ouija board",
    date:  [6,  13,  20,  27,  3],
    time:  ["15:50",  "17:50",  "19:50"],
    length: 136,
    param: "ouija-origin-of-evil",
    background:
      "https://cdn-cc-image-api-p001.cc.vubiquity.com/sf-api/image?i=https://vucscdnprodne.azureedge.net/images/vmest_prod/1/furniture/VX-5841161_1920x1080.PNG?q=80",
  },
];
